export const restaurantList = [
  {
    id:1,
    resname: "kfc",
    cuisines: "biriyani",
    rating: "4",
    time: "30 - 40 mints",
    distance: "koramangala",
    imgsrc: "/restaurant1.avif",
  },
  {
    id:2,
    resname: "dominos",
    cuisines: "biriyani",
    rating: "4.5",
    time: "30 - 40 mints",
    distance: "koramangala",
    imgsrc: "/restaurant1.avif",
  },
  {
    id:3,
    resname: "pizza hut",
    cuisines: "biriyani",
    rating: "3.9",
    time: "30 - 40 mints",
    distance: "koramangala",
    imgsrc: "/restaurant1.avif",
  },
  {
    id:4,
    resname: "kfc",
    cuisines: "biriyani",
    rating: "4.5",
    time: "30 - 40 mints",
    distance: "koramangala",
    imgsrc: "/restaurant1.avif",
  },
];